version: '3'

services: 

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.node
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
       - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules # anonymous volume
                                  # Na hora que cria o volume a cima, substitui todo conteudo,
                                  # no /usr/src/app pelo que esta no diretorio node, removendo
                                  # o diretorio node_modules, o volume anonimo garante que ao
                                  # criar o volume acima, utilize o conteudo do diretorio
                                  # node_modules que esta na image gerada com o Dockerfile,
                                  # onde já foi feito o npm install.
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge      
